### ISSUE TITLE
Why does this now need permissions to drafts and sending emails?

### ISSUE THREAD

**Issue by kapad** [davesteele/gnome-gmail#24]
I was using this extension for a few weeks and it did not ask for any OAuth permissions. I used it successfully without having asking for any permissions. When I clicked on an email link today, it asked me for OAuth permissions. Why are these permissions required? Won't a simple redirect to the correct gmail account, (which I am specifying in the alert box) work as it was working earlier?

**Comment by davesteele** [comment]
The app has used a number of different ways to to access the service. The OAuth-requiring GMail API has been used for a while for links containing message bodies or attachments. The interface is well documented and officially supported.

The URL reference used for simpler requests was reverse-engineered, and has broken in the past, without warning. I removed it to avoid having to deal with that issue again.

You should rarely see the authentication request. Note that it only provides access to working with email drafts.
