### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by simonbcn** [davesteele/gnome-gmail#29]
Firefox 44.0.2
Arch Linux 64 bits

I'm trying to write an email from the link "_Contact Developer_" in this page: http://add0n.com/fastest-gmail.html but it shows this error:
```
Traceback (most recent call last):
  File "/usr/share/gnome-gmail/gnomegmail.py", line 809, in <module>
    main()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 794, in main
    gmailurl = gm_url.gmail_url()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 533, in gmail_url
    gmailurl = self.api_gmail_url()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 500, in api_gmail_url
    gm_api.form_message()
  File "/usr/share/gnome-gmail/gnomegmail.py", line 311, in form_message
    self.message_text = msg.as_bytes()
  File "/usr/lib/python3.5/email/message.py", line 179, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.5/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/lib/python3.5/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.5/email/generator.py", line 214, in _dispatch
    meth(msg)
  File "/usr/lib/python3.5/email/generator.py", line 288, in _handle_multipart
    self._write_lines(preamble)
  File "/usr/lib/python3.5/email/generator.py", line 161, in _write_lines
    self.write(laststripped)
  File "/usr/lib/python3.5/email/generator.py", line 410, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 18: ordinal not in range(128)
```

My locales:
```
LANG=es_ES.utf8
LC_CTYPE=es_ES.utf8
LC_NUMERIC="es_ES.utf8"
LC_TIME="es_ES.utf8"
LC_COLLATE=C
LC_MONETARY="es_ES.utf8"
LC_MESSAGES="es_ES.utf8"
LC_PAPER="es_ES.utf8"
LC_NAME="es_ES.utf8"
LC_ADDRESS="es_ES.utf8"
LC_TELEPHONE="es_ES.utf8"
LC_MEASUREMENT="es_ES.utf8"
LC_IDENTIFICATION="es_ES.utf8"
LC_ALL=
```

**Comment by simonbcn** [comment]
http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by simonbcn** [comment]
The default version of python in Arch is **Python 3.5.1**
If I execute `python2 gnome-gmail.py` it doesn't show the unicode error but it fails in oauth process. It opens my default browser (_Firefox 44.0.2_) with the oauth page but when I press "_Allow_", the browser closes and gnome-gmail shows an error "400: Bad Request".

**Comment by simonbcn** [comment]
If I execute, from console, `gnome-gmail` works and it opens the gmail URL in default browser but if I execute `gnome-gmail any-text` it fails.

**Comment by davesteele** [comment]
For the 400 error, note #10 and #22, patched in 2.0-1.

**Comment by davesteele** [comment]
./gnome-gmail launches a url in a browser. gnome-gmail any-text works with the GMail API, and thus needs OAuth2.

**Comment by simonbcn** [comment]
gnome-gmail is for python 3 or 2?

**Comment by davesteele** [comment]
Python 3 compatibility is recent, and not well tested.

**Comment by simonbcn** [comment]
Ok, I have changed `/usr/bin/gnome-gmail` to execute it with python2 and now it works well.

**Comment by max72bra** [comment]
hi dave,
an arch user of my package has encountered same error. but from console only, supposedly for the use of utf-8 or not. same spanish locale of simonbcn.
culprit is the localization string of the preamble message '_("Mime message attached")' to "Mensaje MIME incluído": accented i except in "UnicodeEncodeError: 'ascii' codec can't encode character... bla bla"
we are testing a patch that i will commit as soon as i have some positive feedback

**Comment by max72bra** [comment]
pull request done. https://github.com/davesteele/gnome-gmail/pull/42

**Comment by max72bra** [comment]
pull https://github.com/davesteele/gnome-gmail/pull/43
this should be conclusive

**Comment by simonbcn** [comment]
It works for me.
