### ISSUE TITLE
gnome-gmail crashes while google first asks to give permission to it.

### ISSUE THREAD

**Issue by HoboPrimate** [davesteele/gnome-gmail#32]
Afterwards, google also asks to paste some code into gnome-gmail, but I don't know where to put it.

This is running the packaged version in fedora 23.

**Comment by davesteele** [comment]
Could you run it from the command line with e.g.

    gnome-gmail mailto:joe@example.com

and send me the output when it crashes?

Does it behave better with e.g.

    python2.7 gnome-gmail mailto:joe@example.com

**Comment by HoboPrimate** [comment]
Sure:

# gnome-gmail mailto:joe@example.com
Segmentation fault (core dumped)

# python2.7 /usr/share/gnome-gmail/gnomegmail.py mailto:joe@example.com
Segmentation fault (core dumped)



2016-03-24 17:50 GMT+00:00 David Steele <notifications@github.com>:

**Comment by HoboPrimate** [comment]
And it crashes immediately with those commands.

**Comment by davesteele** [comment]
Based on your report, it is crashing in either Gtk.main_iteration() or Wnck.Screen.get_default(). Make sure you have the Fedora equivalents installed for python-gi, libgtk-3-bin, and gir1.2-wnck-3.0.

**Comment by HoboPrimate** [comment]
I have now installed archlinux, and gnome-gmail package from AUR doesn't crash anymore. Do we close this one?

**Comment by HoboPrimate** [comment]
Closing this one then.
