### ISSUE TITLE
After giving permission, code appears to paste in application.

### ISSUE THREAD

**Issue by HoboPrimate** [davesteele/gnome-gmail#33]
Not sure if this is because I have two-step authentication in gmail, but when launching gnome-gmail, and giving permission to it, gmail tells me "copy this code, switch to your application and paste it there"(my translation) with some code. Where would I put this code?

Thank you for making this software!

**Comment by davesteele** [comment]
The application is supposed to grab the information from the window you describe, and automatically close it before you get a chance to read it. There is no practical way for you to paste the information manually.

This is not likely related to two-factor authentication.

Are you able to compose emails after this?

**Comment by HoboPrimate** [comment]
No, Iclick a mailto: link, give permission to the application, the code
appears and nothing happens.
If I open directly gnome-gmail, it opens up my gmail though.

Eduardo
2016-03-28 2:25 GMT+01:00 David Steele <notifications@github.com>:

**Comment by davesteele** [comment]
For an Arch Linux issue that would explain this behavior, see #6.

**Comment by hackerb9** [comment]
Not an Arch specific issue. I'm seeing the same bug using Ubuntu Xenial Xerus. 

Timeline:
1. Open Office: File → Send → Email as Attachment
2. In Firefox, Google asks for permission, I click OK
3. Google asks me to please paste the code into my application
4. There is nowhere to paste the code and running gnome-gmail just loads up a new tab of email
5. Eventually I get a notification from gnome-gmail: "Timeout getting OAuth"

**Comment by hackerb9** [comment]
Addendum: while investigating another Gnome Gmail bug, bizarrely the OAuth worked. I'm not sure what, if anything, I did differently from the other half dozen attempts that made it work. Perhaps a clue is that Gnome Gmail then tried to close all my Firefox tabs:
![screenshot from 2017-01-03 06-13-10](https://cloud.githubusercontent.com/assets/10174223/21610385/78900750-d17c-11e6-996c-c00b2bc10af2.png)

Is it supposed to be using a sandboxed browser of some kind?

**Comment by davesteele** [comment]
Ok, here is what I suspect is going on. GG launches the confirmation request in a "new browser window". Once authentication is complete, Google puts the confirmation information in the title for the page. GG is scanning all X window titles, looking for that confirmation. Once it sees it, it closes the window and moves on.

If the confirmation window is actually tabbed, and the confirmation tab is not the active tab, then the window title won't have the required information, and GG won't see it. If you happen to click the tab while the scanning is active, GG succeeds, and you get the warning you included.

Sound plausible? Is the confirmation tab not the active one during the process?

**Comment by davesteele** [comment]
Try https://davesteele.github.io/gnome-gmail/deb/gnome-gmail_2.3-1+ppa1_all.deb.

**Comment by davesteele** [comment]
Also, for all, what is your environment? (i.e. Ubuntu/Unity/Firefox ...)

**Comment by hackerb9** [comment]
Bug occurred using completely standard, freshly installed Ubuntu with Unity. The only thing slightly different was that this was on an iMac, but I can't see how that would affect GG.

The confirmation tab was always focused during the process, IIRC, so that should not be the issue.

**Comment by hackerb9** [comment]
I'm attempting to test this further but having trouble as now GG is showing me "400 Bad API Request" from Google when I click the "Allow" button.

**Comment by hackerb9** [comment]
This Heisenbug keeps popping in and out of existence as I try to observe it. I'm not sure why, but today it is working every time I try.

Perhaps a workaround would be to have GG, instead of showing the OAuth timeout message, open a dialog box asking the user to paste in the code.

**Comment by davesteele** [comment]
I tried out Ubuntu 16.10. There were three bugs associated with this report. They are addressed in [V2.3.1-1](https://davesteele.github.io/gnome-gmail/deb/gnome-gmail_2.3.1-1_all.deb), in the [PPA](https://davesteele.github.io/gnome-gmail/ppa.html).
