### ISSUE TITLE
Using inbox.google.com instead of gmail.com

### ISSUE THREAD

**Issue by rusins** [davesteele/gnome-gmail#36]
Is there any way to specify what url gnome-gmail opens in the web browser? Instead of using regular gmail, I prefer inbox.google.com, and would like to set that as the default website for mail related work.

**Comment by davesteele** [comment]
See #7.

**Comment by rusins** [comment]
Sorry, not sure how I missed that when searching o_O

**Comment by rusins** [comment]
For others wondering, this firefox addon can be used to redirect automatically from gmail to inbox: https://addons.mozilla.org/en-US/firefox/addon/redirector/

**Comment by davesteele** [comment]
If you can get that to properly open drafts, the path to support Inbox directly would be documented.
