### ISSUE TITLE
Installation problems under Ubuntu 15.10

### ISSUE THREAD

**Issue by sojusnik** [davesteele/gnome-gmail#37]
Hey!

When installing the new version of gnome-gmail (2.1-1) from the ppa repository in Ubuntu 15.10, then the following error message appears in synaptic:

> gnome-gmail:
> Hängt ab von: gtk-update-icon-cache  but it is not installable

Any ideas how to solve this?

**Comment by davesteele** [comment]
There's a Debian-only change in 2.1-1, and not much else. I'll fix the repository.

**Comment by uusijani** [comment]
Was there a regression or is gtk-update-icon-cache now a hard dependency? I'm getting this in Ubuntu 16.04 (when using the PPA).

```
The following packages have unmet dependencies:
 gnome-gmail : Depends: gtk-update-icon-cache but it is not installable

```

**Comment by davesteele** [comment]
Used to be there was a dedicated ppa version for Ubuntu. I'm trying to eliminate that, so that it will install from Universe. I've uploaded a new version - give it a try.

**Comment by uusijani** [comment]
@davesteele Yup, installs without a hitch now. Much appreciated!
