### ISSUE TITLE
Inaccurate defaults documentation for browser_options?

### ISSUE THREAD

**Issue by scop** [davesteele/gnome-gmail#39]
The defaults for `browser_options` are documented as:

```python
       #         Chrome - "%action %s"
       #         Mozilla - "-remote openurl(%s%action)"
 ```

However these don't seem to match the actual defaults used in `customize_browser()`.

**Comment by davesteele** [comment]
They are the Python defaults - what was there before the change:

https://github.com/python/cpython/blob/master/Lib/webbrowser.py#L270
https://github.com/python/cpython/blob/master/Lib/webbrowser.py#L247
