### ISSUE TITLE
/etc/resolv.conf used in tests might not exist

### ISSUE THREAD

**Issue by scop** [davesteele/gnome-gmail#57]
/etc/resolv.conf which is used in test_main for attachment testing might not exist when tests are being run within a container or a chroot. Would be better to use some that are known to be present, e.g. gnome-gmail's own in-tree README.md.

**Comment by scop** [comment]
Also, there doesn't seem to be any useful output from the tests when the attachment file doesn't exist. The tests just take a long time and fail with other, generic tracebacks.

```
$ sed -i -e "s|/etc/resolv.conf|/doesnt/exist|" test/test_main.py
$ python setup.py test
# takes a long time, then outputs a bunch of raw failure tracebacks like:
test/test_main.py:74: IndexError
[...]
>           rfc822txt = gnomegmail.GMailAPI.form_message.msgtxt[0]
E           IndexError: list index out of range
```

**Comment by davesteele** [comment]
Adressed in 52a358aea4c9686ebac24c9f91bc2ee58e3757c6, slated for v2.5.
