### ISSUE TITLE
please add an example that shows how to set it up with epiphany-browser

### ISSUE THREAD

**Issue by kapouer** [davesteele/gnome-gmail#61]
After all, epiphany is *the* gnome web browser :)

**Comment by davesteele** [comment]
It uses whatever browser you have set as your "Web" application. Look at Settings->Details->Default Applications (IIRC).

**Comment by kapouer** [comment]
Ok, i guess i didn't get the use for "browser_options".

**Comment by davesteele** [comment]
They only come into play if you want to e.g. change the open behavior (new window vs. new tab).
