### ISSUE TITLE
long time taken to launch gmail window in browser

### ISSUE THREAD

**Issue by yashsaxena** [davesteele/gnome-gmail#69]
When I select a file from the system to be emailed, it take noticeably long time for the application to launch the same in browser window. 

Is it the time while the file is being attached?
If the file is being attached, it would be better the window is launched first while the file attached?

**Comment by davesteele** [comment]
The app is uploading the email, along with the attachment, via the GMail API.

The URL to open cannot be determined until after the upload completes.
