### ISSUE TITLE
GPG signature error

### ISSUE THREAD

**Issue by sojusnik** [davesteele/gnome-gmail#75]
Recently I'm receiving error messages regarding GPG signatures:

> Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://davesteele.github.io/gnome-gmail/repo gnome-gmailppa InRelease: Die folgenden Signaturen waren ungültig: EXPKEYSIG 627EBB290A817A82 David Steele <steele@debian.org>Fehlschlag beim Holen von http://davesteele.github.io/gnome-gmail/repo/dists/gnome-gmailppa/InRelease Die folgenden Signaturen waren ungültig: EXPKEYSIG 627EBB290A817A82 David Steele <steele@debian.org>Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

`wget -q -O - https://davesteele.github.io/key-366150CE.pub.txt | sudo apt-key add - ` doesn't help.

Happens on Ubuntu 19.04.

**Comment by davesteele** [comment]
Hmm. Yes, that signing key just expired. I'll need to either extend its life, or resign the repo with the new key.
