### ISSUE TITLE
GNOME Integration with GMail-Desktop app

### ISSUE THREAD

**Issue by citibeth** [davesteele/gnome-gmail#86]
I'm using the *gmail-desktop* Snap on Ubuntu 20.04LTS:
   https://github.com/oitsjustjose/Gmail-Desktop/issues/6

I would like that app to be GNOME-integrated into Linux. I.e. when I click on a *mailto:* link, I would like the *GMail-Desktop* app to open up, rather than Firefox / etc.  Would it be possible / easy to add this functionality to *gnome-gmail* / *Viagee*?

**Comment by davesteele** [comment]
I have no interest in implementing this. The smap claims to already handle mailto integration in any case.
