### ISSUE TITLE
Google Access blocked: Viagee’s request is invalid - The out-of-band (OOB) flow has been blocked

### ISSUE THREAD

**Issue by Daihaushu** [davesteele/gnome-gmail#93]
>Error 400: invalid_request
>The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an >alternative method.
>Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

>https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

>>Sign in with Google

>>Access blocked: Viagee’s request is invalid

>>xxxxxxx@gmail.com
>>You can’t sign in because Viagee sent an invalid request. You can try again later, or contact the developer about this issue. Learn more about this error
>>If you are a developer of Viagee, see error details.
>>Error 400: invalid_request

**Comment by davesteele** [comment]
GNOME Gmail 2.10 removes OOB.

But, the real answer is that GNOME Gmail has been rebranded as Viagee. You should install the *viagee* package.

**Comment by Daihaushu** [comment]
Let me try that, I just searched for the repository name in the package manager.

**Comment by Daihaushu** [comment]
Thanks for the quick response closing issue, will retest with the proper package.
